USE [master]
GO

/****** Object:  Database [MMTravellers]    Script Date: 16-May-18 12:26:03 AM ******/
CREATE DATABASE [MMTravellers]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MMTravellers', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\MMTravellers.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MMTravellers_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\MMTravellers_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MMTravellers] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MMTravellers].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MMTravellers] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MMTravellers] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MMTravellers] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MMTravellers] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MMTravellers] SET ARITHABORT OFF 
GO

ALTER DATABASE [MMTravellers] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MMTravellers] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MMTravellers] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MMTravellers] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MMTravellers] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MMTravellers] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MMTravellers] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MMTravellers] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MMTravellers] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MMTravellers] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MMTravellers] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MMTravellers] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MMTravellers] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MMTravellers] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MMTravellers] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MMTravellers] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MMTravellers] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MMTravellers] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MMTravellers] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MMTravellers] SET  MULTI_USER 
GO

ALTER DATABASE [MMTravellers] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MMTravellers] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MMTravellers] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MMTravellers] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MMTravellers] SET  READ_WRITE 
GO

