//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyanmarTravellers.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.Tickets = new HashSet<Ticket>();
        }

        public long id { get; set; }
        [DisplayName("Date")]
        [DataType(DataType.Date)]
        public System.DateTime date { get; set; }
        [DisplayName("Bus")]
        public long bus_id { get; set; }
        [DisplayName("From")]
        public string from_id { get; set; }
        [DisplayName("To")]
        public string to_id { get; set; }
        [DisplayName("Departure Time")]
        [DataType(DataType.Time)]
        public System.TimeSpan departure_time { get; set; }
        [DisplayName("Created At")]
        public Nullable<System.DateTime> created_at { get; set; }
        [DisplayName("Updated At")]
        public Nullable<System.DateTime> updated_at { get; set; }
        [DisplayName("Fee Per Seat")]
        public decimal fee_per_seat { get; set; }

        [NotMapped]
        [DisplayName("Busline")]
        public long busline_id { get; set; }

        public virtual Bus Bus { get; set; }
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Tickets { get; set; }
    }
}
